import { render, screen } from '@testing-library/react'
import { describe, expect, it } from 'vitest'
import ActionPlan from '../components/ActionPlan'
import { buildChecklist, DISCLAIMER } from '../lib'
import { CITATION, program, screening } from './fixtures'

const TWO_PROGRAMS = screening([
  program({
    required_documents: [
      { name: 'Pay stubs', why: 'Verify wages', rule_id: 'a' },
      { name: 'Photo ID', why: 'Verify identity', rule_id: 'b' },
    ],
  }),
  program({
    program: 'medicaid',
    program_label: 'NC Medicaid',
    estimated_benefit_cents: null,
    required_documents: [{ name: 'Pay stubs', why: 'Verify wages', rule_id: 'c' }],
  }),
])

describe('buildChecklist', () => {
  it('deduplicates documents across programs by name', () => {
    const checklist = buildChecklist(TWO_PROGRAMS)
    const payStubs = checklist.filter((e) => e.name === 'Pay stubs')
    expect(payStubs).toHaveLength(1)
    expect(payStubs[0].programs).toEqual([
      'FNS (Food and Nutrition Services / SNAP)',
      'NC Medicaid',
    ])
    expect(checklist.map((e) => e.name)).toContain('Photo ID')
  })
})

describe('ActionPlan', () => {
  it('contains disclaimer, apply block, checklist, and footer', () => {
    render(<ActionPlan screening={TWO_PROGRAMS} />)
    expect(screen.getByText(DISCLAIMER)).toBeTruthy()
    // Household county (New Hanover in the fixture) directs the client to
    // their own DSS office.
    expect(screen.getByText(/or visit the New Hanover County DSS office/)).toBeTruthy()
    expect(screen.getByRole('link', { name: 'https://epass.nc.gov' })).toBeTruthy()
    expect(screen.getAllByText(/Pay stubs/)).toHaveLength(1)
    expect(
      screen.getByText(
        'Generated by NC Benefits Navigator (open source) — not affiliated with NC DHHS.',
      ),
    ).toBeTruthy()
  })

  it('numbers citations and lists their URLs as footnotes', () => {
    render(<ActionPlan screening={TWO_PROGRAMS} />)
    // Same citation in both programs → one footnote entry.
    expect(screen.getByText(/example\.com\/fns-810/).textContent).toContain('FNS 810')
    expect(screen.getAllByText('[1]').length).toBeGreaterThanOrEqual(2)
  })

  it('falls back to generic wording when county is unknown', () => {
    const noCounty = {
      ...TWO_PROGRAMS,
      household: { ...TWO_PROGRAMS.household, county: null },
    }
    render(<ActionPlan screening={noCounty} />)
    expect(screen.getByText(/or visit your county DSS office/)).toBeTruthy()
  })

  it('renders hostile household and reason strings inert in the print view', () => {
    const hostile = screening([
      program({
        reasons: [
          {
            rule_id: 'r1',
            text: 'Limit is <script>window.__xss=3</script> [apply](javascript:alert(1))',
            citation: CITATION,
          },
        ],
      }),
    ])
    hostile.household = {
      ...hostile.household,
      county: '<img src=x onerror="window.__xss=4"> Hanover',
    }
    const { container } = render(<ActionPlan screening={hostile} />)

    expect(container.querySelector('script')).toBeNull()
    expect(container.querySelector('img')).toBeNull()
    for (const a of container.querySelectorAll('a')) {
      expect(a.getAttribute('href') ?? '').not.toMatch(/^javascript:/i)
    }
    expect((window as { __xss?: number }).__xss).toBeUndefined()
    // Hostile strings survive as literal text, not markup.
    expect(container.textContent).toContain('<script>window.__xss=3</script>')
    expect(container.textContent).toContain('<img src=x onerror="window.__xss=4"> Hanover')
  })

  it('contains no chat content', () => {
    const { container } = render(<ActionPlan screening={TWO_PROGRAMS} />)
    expect(container.querySelector('.chat')).toBeNull()
    expect(container.textContent).not.toContain('Tell me about the household')
  })
})
