import { render, screen } from '@testing-library/react'
import { describe, expect, it } from 'vitest'
import ActionPlan from '../components/ActionPlan'
import { buildChecklist, DISCLAIMER } from '../lib'
import { program, screening } from './fixtures'

const TWO_PROGRAMS = screening([
  program({
    required_documents: [
      { name: 'Pay stubs', why: 'Verify wages', rule_id: 'a' },
      { name: 'Photo ID', why: 'Verify identity', rule_id: 'b' },
    ],
  }),
  program({
    program: 'medicaid',
    program_label: 'NC Medicaid',
    estimated_benefit_cents: null,
    required_documents: [{ name: 'Pay stubs', why: 'Verify wages', rule_id: 'c' }],
  }),
])

describe('buildChecklist', () => {
  it('deduplicates documents across programs by name', () => {
    const checklist = buildChecklist(TWO_PROGRAMS)
    const payStubs = checklist.filter((e) => e.name === 'Pay stubs')
    expect(payStubs).toHaveLength(1)
    expect(payStubs[0].programs).toEqual([
      'FNS (Food and Nutrition Services / SNAP)',
      'NC Medicaid',
    ])
    expect(checklist.map((e) => e.name)).toContain('Photo ID')
  })
})

describe('ActionPlan', () => {
  it('contains disclaimer, apply block, checklist, and footer', () => {
    render(<ActionPlan screening={TWO_PROGRAMS} />)
    expect(screen.getByText(DISCLAIMER)).toBeTruthy()
    expect(screen.getByText(/or visit your county DSS office/)).toBeTruthy()
    expect(screen.getByRole('link', { name: 'https://epass.nc.gov' })).toBeTruthy()
    expect(screen.getAllByText(/Pay stubs/)).toHaveLength(1)
    expect(
      screen.getByText(
        'Generated by NC Benefits Navigator (open source) — not affiliated with NC DHHS.',
      ),
    ).toBeTruthy()
  })

  it('numbers citations and lists their URLs as footnotes', () => {
    render(<ActionPlan screening={TWO_PROGRAMS} />)
    // Same citation in both programs → one footnote entry.
    expect(screen.getByText(/example\.com\/fns-810/).textContent).toContain('FNS 810')
    expect(screen.getAllByText('[1]').length).toBeGreaterThanOrEqual(2)
  })

  it('contains no chat content', () => {
    const { container } = render(<ActionPlan screening={TWO_PROGRAMS} />)
    expect(container.querySelector('.chat')).toBeNull()
    expect(container.textContent).not.toContain('Tell me about the household')
  })
})
