import { buildChecklist, centsToDollars, DISCLAIMER, EPASS_URL, STATUS_LABELS } from '../lib'
import type { ScreeningResult } from '../types'

/** Printable action plan. Hidden on screen; shown alone via @media print. */
export default function ActionPlan({ screening }: { screening: ScreeningResult }) {
  // Footnote numbers assigned per unique citation URL, in document order.
  const footnotes: { url: string; label: string }[] = []
  const numberByUrl = new Map<string, number>()
  for (const program of screening.programs) {
    for (const reason of program.reasons) {
      const { url, manual, section, title } = reason.citation
      if (!numberByUrl.has(url)) {
        numberByUrl.set(url, footnotes.length + 1)
        footnotes.push({ url, label: `${manual} ${section} — ${title}` })
      }
    }
  }
  const checklist = buildChecklist(screening)

  return (
    <div className="action-plan">
      <h1>Benefits screening — action plan</h1>
      <p className="plan-date">Prepared {new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}</p>

      {screening.programs.map((program) => (
        <section key={program.program}>
          <h2>
            {program.program_label}: {STATUS_LABELS[program.status]}
          </h2>
          {program.estimated_benefit_cents !== null && (
            <p>{centsToDollars(program.estimated_benefit_cents)}/month estimated</p>
          )}
          <ul>
            {program.reasons.map((reason, i) => (
              <li key={reason.rule_id + i}>
                {reason.text}
                <sup>[{numberByUrl.get(reason.citation.url)}]</sup>
              </li>
            ))}
          </ul>
        </section>
      ))}

      {checklist.length > 0 && (
        <section>
          <h2>Documents to bring</h2>
          <ul className="checklist">
            {checklist.map((entry) => (
              <li key={entry.name}>
                <span className="checkbox">☐</span> <strong>{entry.name}</strong> — {entry.why}{' '}
                <em>({entry.programs.join(', ')})</em>
              </li>
            ))}
          </ul>
        </section>
      )}

      <section>
        <h2>How to apply</h2>
        <p>
          Apply online at <a href={EPASS_URL}>{EPASS_URL}</a> or visit your county DSS office.
        </p>
      </section>

      <p className="plan-disclaimer">{DISCLAIMER}</p>

      {footnotes.length > 0 && (
        <section className="footnotes">
          <h2>Sources</h2>
          <ol>
            {footnotes.map((note, i) => (
              <li key={note.url + i}>
                {note.label} — {note.url}
              </li>
            ))}
          </ol>
        </section>
      )}

      <p className="plan-footer">
        Generated by NC Benefits Navigator (open source) — not affiliated with NC DHHS.
      </p>
    </div>
  )
}
